replicaCount: 1
image:
  repository: driveopssurya/nodejs-app
  tag: 0177cff935734b710ef6a95a74d4597b9ffc2f70
  pullPolicy: Always
imagePullSecrets:
  - name: regcred
service:
  name: nodejs-service
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  className: alb
  host: my-art.sbs
  certificateArn: arn:aws:acm:ap-south-1:213615930222:certificate/0d41bf59-6160-4295-8298-5d2fa81efc0f
namespace: qa
database:
  host: mysql
mysqlService:
  name: mysql
  port: 3306
