replicaCount: 1

image:
  repository: driveopssurya/nodejs-app
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

service:
  name: nodejs-service
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: alb
  host: my-art.sbs
  certificateArn: arn:aws:acm:ap-south-1:213615930222:certificate/18ada32e-6be2-4408-ad77-a4d7e0757209

namespace: qa

database:
  host: mysql

mysqlService:
  name: mysql
  port: 3306